# Generated by Django 5.0.6 on 2024-05-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Отделы', 'verbose_name_plural': 'Отдел'},
        ),
    ]
